---
- name: Terminate an EC2 instance
  hosts: localhost
  gather_facts: True
  tasks:
    - name: Terminate instance
      ec2:
         instance_ids: ami-0e12cbde3e77cbb98
         wait: true
         state: absent
         region: eu-west-1
      register: ec2
    - name: Print all ec2 variables
      debug: var=ec2
